### ISSUE TITLE
Using another version of bowtie does work for phasTER?

### ISSUE THREAD

**Issue by pokhrelsuresh** [atulkakrana/PHASworks#1]
__Hi Atul, 
I was trying to run the phasTER in wheat small RNA libraries, phasTER couldn't able to build the index for wheat genome which is 3.6 GB. Because the default bowtie version in tarkan has limitation of around or less than 4GB. So I used higher version of bowtie, bowtie-1.1.2, and ran the phasTER, it builds the index but it cannot process further it search for .ebwt file but for large genome bowtie outputs .ebwtl files.
the error message was: 
Traceback (most recent call last):
  File "phaser.py", line 969, in <module>
  File "phaser.py", line 833, in main
  File "phaser.py", line 595, in indexBuilder
FileNotFoundError: [Errno 2] No such file or directory: '~/index/Triticum_aestivum.TGACv1.dna.toplevel.clean.1.ebwt'
Can you please help to sort out this isssue?__

**Comment by atulkakrana** [comment]
Hello Suresh,

The latest version of phasTER  (rc.v2.2) works with all version of Bowtie 1.0 including version 0.12.8.xx. I do not think it is a bowtie issue. 

I will need your settings file (phaser.set) to assist you with this issue. Can you post the contents of phaser.set here?

Atul

**Comment by pokhrelsuresh** [comment]
Hi Atul,
I am using version phasTER (rc.v2.2). Please see the phaser.set file.
<<< Settings file for phaser script >>>

<<< Mandatory Settings, value in text, see descriptions below >>>
@runType        = G
@reference      = ./Triticum_aestivum.TGACv1.dna.toplevel.fa
@userLibs       = SRR1.txt,SRR6.txt,SRR7.txt,SRR8.txt,SRR9.txt,SRR2.txt,
@libFormat      = T
@phase          = 21

<<< Optional Settings, leave empty to make index on fly, value in text>>>
@index          = 

<<<Settings Help>>>
<@runType       - G: Running on whole genome | T: running on transcriptome | S: running on scaffolded genome>
<@reference     - If @runType = âGâ then genome FASTA |  @runType = âSâ or âTâ then your scaffolds or transcriptome FASTA>
<@userLibs      - Specify library IDs in comma separated format to fetch data. Used only if @fetchLib setting is set to "N">
<@libFormat     - Specify the sRNA library format. F: FASTA Format | T: Tag count format>
<@phase         - Desired phase to use for prediction. 21 for 21 nt PHAS | 24 for 24 nt PHAS>
<@index         - If bowtie index exist already provide the path and index suffix. If not, then leave blank, the index will be made in first run and will be reused in subsequent runs>

<<<END>>>
<<<Script for predicting lib-wise phased loci>>>
<<<v1.0>>>
<<<Author: kakrana@gmail.com>>>

**Comment by atulkakrana** [comment]
Hi Suresh,

Wheat genome has more than 4 billion nucleotides. So, **Bowtie** makes a special *large index* for wheat genome. These *large index* files have different extensions and that's the reason for issue you are facing.  I will update the script to accept these slightly different files. You can expect and updated script by the end of this week.

Thanks for reporting the issue.

Atul

**Comment by pokhrelsuresh** [comment]
Hi Atul,
Thanks for working on this.  I will be waiting for the updated script.

Suresh

**Comment by atulkakrana** [comment]
The issue has been resolved in latest version (rc v3 or above). This version is not released yet but can be downloaded directly from here: https://github.com/atulkakrana/PHASworks

Just click on green button 'clone or download' on top-right side of page and choose to 'Download as Zip'.

Best

Atul
