### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by pokhrelsuresh** [atulkakrana/PHASworks#2]
Hi Atul,
While running phasTER, I got stuck into a weird issue: ** Problem with Phasing script - Return code not 0

Cannot fork: Cannot allocate memory at /usr/local/perls/lib/site_perl/5.20.0/Parallel/ForkManager.pm line 515, <DATA> line 7791362.
Cannot fork: Cannot allocate memory at /usr/local/perls/lib/site_perl/5.20.0/Parallel/ForkManager.pm line 515, <DATA> line 8033261.
Cannot fork: Cannot allocate memory at /usr/local/perls/lib/site_perl/5.20.0/Parallel/ForkManager.pm line 515, <DATA> line 6822425.
Cannot fork: Cannot allocate memory at /usr/local/perls/lib/site_perl/5.20.0/Parallel/ForkManager.pm line 515, <DATA> line 6170777.
Cannot fork: Cannot allocate memory at /usr/local/perls/lib/site_perl/5.20.0/Parallel/ForkManager.pm line 515, <DATA> line 6252872.
And the program terminates automatically without giving phased loci.
Can you please help me to find the solution.

Thanks,
Suresh

**Comment by atulkakrana** [comment]
Hello Suresh,

You didn't include the settings file so I can't tell you what exactly went wrong but it seems that you have used genome mode for a genome with lots of scaffolds. Please check the reference fasta file for number of chromosomes, if they are many (>50) than use correct value for '@runType' parameter in your phaser.set (settings file). 

Atul

**Comment by pokhrelsuresh** [comment]
Hi Atul,
Thanks for the suggestions. The genome has more scaffolds than 50. I will change @runType and run it again.

Thank you very much

Suresh

**Comment by atulkakrana** [comment]
Ok. I am pasting the description of @runType parameter below:

<@runType       - G: Running on whole genome | T: running on transcriptome | S: running on scaffolded genome>

Atul

**Comment by pokhrelsuresh** [comment]
Hi Atul, 
I ran the phasTER with @runType S, for scaffolded genome, it still give me warnings:
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps
Warning: Encountered reference sequence with only gaps

And this is the error:
Argument "seq_4094523\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0..." isn't numeric in numeric le (<=) at /home/suresh/.phaster/phasclust.MUL.v2.pl line 289, <IN> line 6564.
Use of uninitialized value $array[7] in concatenation (.) or string at /home/suresh/.phaster/phasclust.MUL.v2.pl line 324, <TEMP2> line 6564.
Use of uninitialized value $array[8] in concatenation (.) or string at /home/suresh/.phaster/phasclust.MUL.v2.pl line 324, <TEMP2> line 6564.
Use of uninitialized value within %hits in concatenation (.) or string at /home/suresh/.phaster/phasclust.MUL.v2.pl line 324, <TEMP2> line 6564.
Use of uninitialized value $abun in addition (+) at /home/suresh/.phaster/phasclust.MUL.v2.pl line 721.
Use of uninitialized value $len in numeric eq (==) at /home/suresh/.phaster/phasclust.MUL.v2.pl line 722.
Use of uninitialized value in division (/) at /home/suresh/.phaster/phasclust.MUL.v2.pl line 723.
Use of uninitialized value $abun in division (/) at /home/suresh/.phaster/phasclust.MUL.v2.pl line 723.
Illegal division by zero at /home/suresh/.phaster/phasclust.MUL.v2.pl line 723.

** Problem with Phasing script - Return code not 0

And it didn't complete the run.

**Comment by atulkakrana** [comment]
I need phaser.set to be able to help you.

Atul

**Comment by pokhrelsuresh** [comment]
Hi Atul,
This is the phaser.set file.
<<< Settings file for phaser script >>>

<<< Mandatory Settings, value in text, see descriptions below >>>
@runType = S
@reference = ./Lettuce_genome.fa
@userLibs = 6010_chopped.txt,6011_chopped.txt,
@libFormat = T
@phase = 24

<<< Optional Settings, leave empty to make index on fly, value in text>>>
@index =

<<>>
<@runType - G: Running on whole genome | T: running on transcriptome | S: running on scaffolded genome>
<@reference - If @runType = âGâ then genome FASTA | @runType = âSâ or âTâ then your scaffolds or transcriptome FASTA>
<@userLibs - Specify library IDs in comma separated format to fetch data. Used only if @fetchLib setting is set to "N">
<@libFormat - Specify the sRNA library format. F: FASTA Format | T: Tag count format>
<@phase - Desired phase to use for prediction. 21 for 21 nt PHAS | 24 for 24 nt PHAS>
<@index - If bowtie index exist already provide the path and index suffix. If not, then leave blank, the index will be made in first run and will be reused in subsequent runs>

<<>>

Thanks,
Suresh

**Comment by atulkakrana** [comment]
Were you able to fix this by running phaser w/o your index i.e. a clean run?

Atul

**Comment by atulkakrana** [comment]
No response from user. The issue was due to wrong mode selected by user. User selected genome while reference had scaffolds. Resolving the issue.
